# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14bb01b6a29b22281a0a2bd0784492d6156f4f1372c574a84daf783cd736ce0736d454474914f52f8f6fb4e54eae1d052cfea8a553a694edc6ce95562e9b20a2

test:
  secret_key_base: 2bc9d63c82854f65dfbff8db4956858624510d9a9733dad3639448aa67fe2230bcfeda64a91c04c9a3edfa840695018f7148dc83cbada8698b7102a15a8238f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
